### PR TITLE
Add helm

### PR DESCRIPTION
**Pull request by pacmessica**

### CODE REVIEW

**Comment by pacmessica** [comment]
Not sure how you created the helm.lock file [her](https://github.com/figment-networks/indexer-search/blob/feature/docker%2Bk8s/helm/indexer-search/Chart.lock)

I suspect it's auto creating when adding deps via helm, but I got an error:
```
➜  indexer-manager git:(feat/k8s) ✗ helm repo add common https://raw.githubusercontent.com/figment-networks/helm/main/_repo
Error: looks like "https://raw.githubusercontent.com/figment-networks/helm/main/_repo" is not a valid chart repository or cannot be reached: failed to fetch https://raw.githubusercontent.com/figment-networks/helm/main/_repo/index.yaml : 404 Not Found
```

**Comment by lukanus** [comment]
The problem you have with that is from the configuration, this entire process is described in notion docs

**Comment by pacmessica** [comment]
> The problem you have with that is from the configuration, this entire process is described in notion docs

I see, so you're supposed to copy the chart.lock. I was looking at the instructions on the helm repo in github + official helm docs

**Comment by pacmessica** [comment]
oof a lot of clean up. I missed a bunch :/

**Comment by lukanus** [comment]
I can create PR to your PR to the PR if you like :)

**Comment by pacmessica** [comment]
> I can create PR to your PR to the PR if you like :)

haha no, that's fine- I can see the diff. Figured I missed some things just didn't realize I missed this much 😳. devops is not my strong suit

**Pull request merged**
